version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: localca-backend
    volumes:
      - localca-data:/app/data
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8555:8555"
    environment:
      - LOCALCA_DATA_DIR=/app/data
      - LOCALCA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - localca-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: localca-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - localca-network

volumes:
  localca-data:
    name: localca-data

networks:
  localca-network:
    name: localca-network