version: '3.8'

services:
  localca:
    container_name: localca
    hostname: ca
    domainname: local.local
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"  # For HTTPS
    volumes:
      - ./data:/app/certs
      - ./cakey.txt:/run/secrets/cakey:ro  # Mount CA key as read-only
    environment:
      - CA_NAME=ca.homelab.local  # Name of the CA including domain (FQDN)
      - CA_KEY_FILE=/run/secrets/cakey
      - ORGANIZATION=LocalCA
      - COUNTRY=US  # Country code
      - EMAIL_NOTIFY=false
      - TLS_ENABLED=true  # Enable HTTPS
    networks:
      - localca-network
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8443"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  localca-network:
    driver: bridge