version: '3.8'

services:
  backend-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: localca-backend-test
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./test-data:/app/data
    environment:
      - DATA_DIR=/app/data
      - LOCALCA_DATA_DIR=/app/data
      - LOCALCA_HOST=0.0.0.0
      - CA_NAME=LocalCA Test
      - ORGANIZATION=LocalCA Test Org
      - COUNTRY=US
      - TLS_ENABLED=false
      - EMAIL_NOTIFY=false
      - DEBUG=true
      - CA_KEY_FILE=/app/data/cakey.txt
      - CORS_ALLOWED_ORIGINS=http://localhost:*,https://localhost:*,http://127.0.0.1:*,https://127.0.0.1:*
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOWED_HEADERS=Content-Type,Authorization,X-CSRF-Token
      - CSRF_EXEMPT_PATHS=/api/
      - GIN_MODE=debug
      - COOKIE_DOMAIN=
      - COOKIE_SECURE=false
      - ALLOW_LOCALHOST=true
      # Disable external services for testing
      - DATABASE_ENABLED=false
      - S3_ENABLED=false
      - CACHE_ENABLED=false
      # Logging Configuration
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - LOG_OUTPUT=stdout
    restart: unless-stopped
    networks:
      - localca-test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/ca-info"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

networks:
  localca-test-network:
    name: localca-test-network 