version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: localca-backend
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8555:8555"
    environment:
      - LOCALCA_DATA_DIR=/app/data
      - LOCALCA_HOST=0.0.0.0
      - CA_NAME=LocalCA in.lc
      - ORGANIZATION=LocalCA
      - COUNTRY=US
      - TLS_ENABLED=true
      - EMAIL_NOTIFY=false
      - BASE_DOMAIN=in.lc
      - DEBUG=true
      - CA_KEY_FILE=/app/data/cakey.txt
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000,http://127.0.0.1:3000
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOWED_HEADERS=Content-Type,Authorization,X-CSRF-Token
      - CSRF_EXEMPT_PATHS=/api/
      - GIN_MODE=debug
      - COOKIE_DOMAIN=
      - COOKIE_SECURE=false
    restart: unless-stopped
    networks:
      - localca-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: localca-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_DOMAIN=in.lc
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - localca-network

volumes:
  localca-data:
    name: localca-data

networks:
  localca-network:
    name: localca-network