# version: '3.8'  # Version field is obsolete and removed

services:
  # Test the Go backend
  backend-test:
    build:
      context: ..
      dockerfile: build/Dockerfile.test-backend
    volumes:
      - ../:/app
      - go-mod-cache:/go/pkg/mod
    environment:
      - CGO_ENABLED=0
      - LOCALCA_TEST_MODE=true
      - GO_NO_BLOAT_OUTPUT=1 # Reduce Go output verbosity
    # The entrypoint script now handles the test command
    # No need to specify command here

  # Test the frontend
  frontend-test:
    build:
      context: ..
      dockerfile: build/Dockerfile.test-frontend
    volumes:
      - ../:/app
      - node-modules:/app/node_modules
    environment:
      - NODE_ENV=test
      - NODE_OPTIONS=--no-warnings
    # The entrypoint script now handles the configuration and testing

  # Build the application to verify it works
  build-check:
    build:
      context: ..
      dockerfile: build/Dockerfile.test-build
    volumes:
      - ../:/app
      - go-mod-cache:/go/pkg/mod
      - node-modules:/app/node_modules
    # The embedded script now handles verification steps

volumes:
  go-mod-cache:
  node-modules: 