name: Cache Cleanup

on:
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight every Sunday
  workflow_dispatch:  # Allow manual triggering

jobs:
  cleanup:
    name: Cleanup Caches
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cleanup
        uses: actions/github-script@v7
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            if (!caches.data.actions_caches || caches.data.actions_caches.length === 0) {
              console.log('No caches found to clean up');
              return;
            }
            
            // Get caches older than 7 days
            const cutoffDate = new Date();
            cutoffDate.setDate(cutoffDate.getDate() - 7);
            
            let deletedCount = 0;
            for (const cache of caches.data.actions_caches) {
              const cacheDate = new Date(cache.created_at);
              if (cacheDate < cutoffDate) {
                console.log(`Deleting cache ${cache.key}, created at ${cache.created_at}`);
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id
                });
                deletedCount++;
              }
            }
            
            console.log(`Deleted ${deletedCount} caches`); 