name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Run package tests
        run: go test -v -cover ./pkg/...

      - name: Run main tests
        run: go test -v -cover .

  docker:
    name: Build and Push Docker Images
    needs: test
    runs-on: ubuntu-latest
    # Only run this job on main branch or tags, not on PRs
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tags
        id: tags
        run: |
          # Convert repository name to lowercase
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "BACKEND_TAGS=ghcr.io/${REPO_LOWER}/backend:latest,ghcr.io/${REPO_LOWER}/backend:${VERSION}" >> $GITHUB_ENV
            echo "FRONTEND_TAGS=ghcr.io/${REPO_LOWER}/frontend:latest,ghcr.io/${REPO_LOWER}/frontend:${VERSION}" >> $GITHUB_ENV
          else
            echo "BACKEND_TAGS=ghcr.io/${REPO_LOWER}/backend:unstable" >> $GITHUB_ENV
            echo "FRONTEND_TAGS=ghcr.io/${REPO_LOWER}/frontend:unstable" >> $GITHUB_ENV
          fi

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.BACKEND_TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=LocalCA Backend - Certificate Authority Management Tool
            org.opencontainers.image.licenses=Dual License: Free for Self-Hosting / Commercial License Required
            org.opencontainers.image.vendor=lazarev.cloud
            org.opencontainers.image.authors=lazarevtill
            org.opencontainers.image.title=LocalCA Backend
            org.opencontainers.image.url=https://lazarev.cloud

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.frontend
          push: true
          tags: ${{ env.FRONTEND_TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=LocalCA Frontend - Certificate Authority Management UI
            org.opencontainers.image.licenses=Dual License: Free for Self-Hosting / Commercial License Required
            org.opencontainers.image.vendor=lazarev.cloud
            org.opencontainers.image.authors=lazarevtill
            org.opencontainers.image.title=LocalCA Frontend
            org.opencontainers.image.url=https://lazarev.cloud
            