name: Dependency Review

on:
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail the workflow if high-severity vulnerabilities are found
          fail-on-severity: high
          
          # Fail on vulnerabilities in production dependencies
          fail-on-scopes: runtime 