# This file is deprecated and has been replaced by ci-cd.yml
name: Deprecated
on:
  workflow_dispatch:

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecated workflow
        run: echo "This workflow is deprecated and has been replaced by ci-cd.yml" 