name: Generate SPDX SBOM

on:
  push:
    branches: [ main ]
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'package.json'
      - 'package-lock.json'
  schedule:
    - cron: '0 0 * * 1' # Run weekly on Monday at midnight UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate-sbom:
    name: Generate SPDX SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to commit the SBOM file
      id-token: write  # Required for provenance
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Syft
        uses: anchore/sbom-action/download-syft@v0
        
      - name: Generate combined SBOM
        run: |
          # Generate SBOM in SPDX format
          ./syft . -o spdx-json=combined-sbom.spdx.json
      
      - name: Generate Go dependencies SBOM
        run: |
          # Specifically focus on Go dependencies
          ./syft packages . -o spdx-json=go-deps-sbom.spdx.json
      
      - name: Generate dependency submission
        uses: advanced-security/spdx-dependency-submission-action@v1.0.0
        with:
          filePath: "combined-sbom.spdx.json"
          
      - name: Sign SBOM with Sigstore
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: combined-sbom.spdx.json go-deps-sbom.spdx.json
          signature-artifact: sbom-signatures
        
      - name: Create attestation
        run: |
          echo "combined-sbom.spdx.json" > sbom-files.txt
          echo "go-deps-sbom.spdx.json" >> sbom-files.txt
          sha256sum combined-sbom.spdx.json go-deps-sbom.spdx.json > sbom-checksums.txt

      - name: Upload SBOMs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sboms
          path: |
            combined-sbom.spdx.json
            go-deps-sbom.spdx.json
            sbom-checksums.txt
            sbom-files.txt
          retention-days: 90
          
      - name: Commit SBOM to repository
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update SPDX SBOM [skip ci]"
          file_pattern: "combined-sbom.spdx.json SPDX.json"
          commit_user_name: "SBOM Bot"
          commit_user_email: "sbom-bot@lazarev.cloud"
          branch: ${{ github.head_ref || github.ref_name }} 